=== LHS2S6/lhs2s6xmlGyak/lhs2s6_10_08/ERkonvScema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="A">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="b"/>
				<xs:element ref="c"/>
			</xs:sequence>
			<xs:attribute name="a" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="AB">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="A_a"/>
				<xs:element ref="B_a"/>
				<xs:element ref="c"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="A_a">
		<xs:complexType/>
	</xs:element>
	<xs:element name="B">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="b"/>
			</xs:sequence>
			<xs:attribute name="a" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="B_a">
		<xs:complexType/>
	</xs:element>
	<xs:element name="C">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="b"/>
			</xs:sequence>
			<xs:attribute name="a" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ER">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="A"/>
				<xs:element ref="B"/>
				<xs:element ref="C"/>
				<xs:element ref="AB"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="b">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="x"/>
				<xs:element ref="y"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="c">
		<xs:complexType/>
	</xs:element>
	<xs:element name="x">
		<xs:complexType/>
	</xs:element>
	<xs:element name="y">
		<xs:complexType/>
	</xs:element>
</xs:schema>

=== LHS2S6/lhs2s6xmlGyak/Lhs2s6_10_08/erkonv.xml
<?xml version="1.0" encoding="UTF-8"?>
<ER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/!Gyakorlatok/XMLGyak/GIT/lhs2s6_10_08/ERkonvScema.xsd">
	<A a="">
		<b>
			<x/>
			<y/>
		</b>
		<c/>
	</A>
	<B a="">
		<b>
			<x/>
			<y/>
		</b>
	</B>
	<C a="">
		<b/>
	</C>
	<AB>
		<A_a/>
		<B_a/>
		<c/>
	</AB>
</ER>
