=== LHS2S6/lhs2s6xmlGyak/Lhs2s6_10_15/ERtoXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<xs:element name="fo">
	<xs:complexType>
	<xs:sequence>
		<xs:element name="A" maxOccurs="unbounded">
			<xs:complexType mixed="true">
				<xs:sequence>
					<xs:element name="B" type="xs:string"/>
					<xs:element name="C" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="a1" type="xs:int"/>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="B" maxOccurs="unbounded">
			<xs:complexType mixed="true">
				<xs:attribute name="b1" type="xs:int"/>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="C" maxOccurs="unbounded">
			<xs:complexType mixed="true">
				<xs:attribute name="c1" type="xs:int"/>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="AB" maxOccurs="unbounded">
			<xs:complexType mixed="true">
				<xs:attribute name="ab1" type="xs:int"/>
				<xs:attribute name="ab2" type="xs:int"/>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="BC" maxOccurs="unbounded">
			<xs:complexType mixed="true">
				<xs:attribute name="bc1" type="xs:int"/>
				<xs:attribute name="bc2" type="xs:int"/>
			</xs:complexType>
		</xs:element>
		
	</xs:sequence>
	</xs:complexType>
	
	<xs:key name="K1">
		<xs:selector xpath="A"/>
		<xs:field xpath="@a1"/>
	</xs:key>
	
	<xs:key name="K2">
		<xs:selector xpath="B"/>
		<xs:field xpath="@b1"/>
	</xs:key>
	
	<xs:key name="K3">
		<xs:selector xpath="B"/>
		<xs:field xpath="@b1"/>
	</xs:key>
	
	<xs:key name="K4">
		<xs:selector xpath="C"/>
		<xs:field xpath="@c1"/>
	</xs:key>
	
	<xs:keyref name="K11" refer="K1">
		<xs:selector xpath="AB"/>
		<xs:field xpath="@AB1"/>
	</xs:keyref>
	
	<xs:keyref name="K12" refer="K2">
		<xs:selector xpath="AB"/>
		<xs:field xpath="@ab2"/>
	</xs:keyref>
	
	<xs:keyref name="K21" refer="K3">
		<xs:selector xpath="BC"/>
		<xs:field xpath="@bc1"/>
	</xs:keyref>
	
	<xs:keyref name="K22" refer="K4">
		<xs:selector xpath="BC"/>
		<xs:field xpath="@bc2"/>
	</xs:keyref>
	
</xs:element>


</xs:schema>

=== LHS2S6/lhs2s6xmlGyak/Lhs2s6_10_15/ERtoXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<fo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="ERtoXSD.xsd">
	<A a1="1">
		<B>
			
		</B>
		<C>
		</C>
	</A>
	
	
	<B b1="2">
	</B>	
	
	<C c1="3">
	
	</C>
	
	<AB ab1="1" ab2="2">
	
	</AB>
	
	<BC bc1="2" bc2="3">
	
	</BC>
	
	
</fo>
