=== LHS2S6/lhs2s6xmlGyak/XML_FélévesFeladat_LHS2S6/f1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="f1">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="csapat" maxOccurs="10">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="csapatnev" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="200"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="csapatpont" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="1000"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:key name="csapat_PrimaryKey_1">
						<xs:selector xpath="."/>
						<xs:field xpath="id"/>
					</xs:key>
				</xs:element>
				<xs:element name="eredmeny" maxOccurs="1000">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="1000"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="nagydijid" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="25"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="helyezes" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="rajtszam" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="99"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="csapatid" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="pontszam" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="26"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:key name="eredmeny_PrimaryKey_1">
						<xs:selector xpath="."/>
						<xs:field xpath="id"/>
					</xs:key>
				</xs:element>
				<xs:element name="kapcs" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="csapat" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="nagydij" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="25"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="nagydij" maxOccurs="25">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="25"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="nev" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="300"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="idopont" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:date">
										<xs:minInclusive value="2019-01-01"/>
										<xs:maxInclusive value="2019-12-31"/>
										<xs:pattern value="\p{Nd}{4}-\p{Nd}{2}-\p{Nd}{2}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:key name="nagydij_PrimaryKey_1">
						<xs:selector xpath="."/>
						<xs:field xpath="id"/>
					</xs:key>
				</xs:element>
				<xs:element name="versenyzo" maxOccurs="20">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="rajtszam">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="99"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="nev" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="100"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="pont" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="500"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="csapatid" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:key name="versenyzo_PrimaryKey_1">
						<xs:selector xpath="."/>
						<xs:field xpath="rajtszam"/>
					</xs:key>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== LHS2S6/lhs2s6xmlGyak/XML_FélévesFeladat_LHS2S6/f1.xml
<?xml version="1.0" encoding="UTF-8"?>
<f1 xsi:noNamespaceSchemaLocation="file:///C:/Users/poczo/Desktop/xml%20beadando/f1.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<csapat>
		<id>1</id>
		<csapatnev>Mercedes AMG Petronas</csapatnev>
		<csapatpont>100</csapatpont>
	</csapat>
	<csapat>
		<id>2</id>
		<csapatnev>Scuderia Ferrari</csapatnev>
		<csapatpont>50</csapatpont>
	</csapat>
	<csapat>
		<id>3</id>
		<csapatnev>RedBull Racing Honda</csapatnev>
		<csapatpont>70</csapatpont>
	</csapat>
	<csapat>
		<id>4</id>
		<csapatnev>Mclaren Renault</csapatnev>
		<csapatpont>40</csapatpont>
	</csapat>
	<eredmeny>
		<id>1</id>
		<nagydijid>1</nagydijid>
		<helyezes>1</helyezes>
		<rajtszam>44</rajtszam>
		<csapatid>1</csapatid>
		<pontszam>26</pontszam>
	</eredmeny>
	<eredmeny>
		<id>2</id>
		<nagydijid>1</nagydijid>
		<helyezes>2</helyezes>
		<rajtszam>77</rajtszam>
		<csapatid>1</csapatid>
		<pontszam>18</pontszam>
	</eredmeny>
	<eredmeny>
		<id>3</id>
		<nagydijid>1</nagydijid>
		<helyezes>3</helyezes>
		<rajtszam>33</rajtszam>
		<csapatid>3</csapatid>
		<pontszam>15</pontszam>
	</eredmeny>
	<eredmeny>
		<id>4</id>
		<nagydijid>1</nagydijid>
		<helyezes>4</helyezes>
		<rajtszam>5</rajtszam>
		<csapatid>2</csapatid>
		<pontszam>12</pontszam>
	</eredmeny>
	<eredmeny>
		<id>5</id>
		<nagydijid>1</nagydijid>
		<helyezes>5</helyezes>
		<rajtszam>16</rajtszam>
		<csapatid>2</csapatid>
		<pontszam>10</pontszam>
	</eredmeny>
	<eredmeny>
		<id>6</id>
		<nagydijid>1</nagydijid>
		<helyezes>6</helyezes>
		<rajtszam>23</rajtszam>
		<csapatid>3</csapatid>
		<pontszam>8</pontszam>
	</eredmeny>
	<eredmeny>
		<id>7</id>
		<nagydijid>2</nagydijid>
		<helyezes>1</helyezes>
		<rajtszam>77</rajtszam>
		<csapatid>1</csapatid>
		<pontszam>25</pontszam>
	</eredmeny>
	<eredmeny>
		<id>8</id>
		<nagydijid>2</nagydijid>
		<helyezes>2</helyezes>
		<rajtszam>33</rajtszam>
		<csapatid>3</csapatid>
		<pontszam>19</pontszam>
	</eredmeny>
	<eredmeny>
		<id>9</id>
		<nagydijid>2</nagydijid>
		<helyezes>3</helyezes>
		<rajtszam>44</rajtszam>
		<csapatid>1</csapatid>
		<pontszam>15</pontszam>
	</eredmeny>
	<eredmeny>
		<id>10</id>
		<nagydijid>2</nagydijid>
		<helyezes>4</helyezes>
		<rajtszam>16</rajtszam>
		<csapatid>2</csapatid>
		<pontszam>12</pontszam>
	</eredmeny>
	<eredmeny>
		<id>11</id>
		<nagydijid>2</nagydijid>
		<helyezes>5</helyezes>
		<rajtszam>23</rajtszam>
		<csapatid>3</csapatid>
		<pontszam>10</pontszam>
	</eredmeny>
	<eredmeny>
		<id>12</id>
		<nagydijid>2</nagydijid>
		<helyezes>6</helyezes>
		<rajtszam>5</rajtszam>
		<csapatid>2</csapatid>
		<pontszam>8</pontszam>
	</eredmeny>
	<kapcs>
		<csapat>1</csapat>
		<nagydij>1</nagydij>
	</kapcs>
	<kapcs>
		<csapat>2</csapat>
		<nagydij>1</nagydij>
	</kapcs>
	<kapcs>
		<csapat>3</csapat>
		<nagydij>1</nagydij>
	</kapcs>
	<kapcs>
		<csapat>1</csapat>
		<nagydij>2</nagydij>
	</kapcs>
	<kapcs>
		<csapat>2</csapat>
		<nagydij>2</nagydij>
	</kapcs>
	<kapcs>
		<csapat>3</csapat>
		<nagydij>2</nagydij>
	</kapcs>
	<nagydij>
		<id>1</id>
		<nev>Ausztrál nagydíj</nev>
		<idopont>2019-03-17</idopont>
	</nagydij>
	<nagydij>
		<id>2</id>
		<nev>Bahrain nagydíj</nev>
		<idopont>2019-03-31</idopont>
	</nagydij>
	<versenyzo>
		<rajtszam>4</rajtszam>
		<nev>Lando Norris</nev>
		<pont>20</pont>
		<csapatid>4</csapatid>
	</versenyzo>
	<versenyzo>
		<rajtszam>5</rajtszam>
		<nev>Sebastian Vettel</nev>
		<pont>20</pont>
		<csapatid>2</csapatid>
	</versenyzo>
	<versenyzo>
		<rajtszam>16</rajtszam>
		<nev>Charles Leclerc</nev>
		<pont>30</pont>
		<csapatid>2</csapatid>
	</versenyzo>
	<versenyzo>
		<rajtszam>23</rajtszam>
		<nev>Alexander Albon</nev>
		<pont>20</pont>
		<csapatid>3</csapatid>
	</versenyzo>
	<versenyzo>
		<rajtszam>33</rajtszam>
		<nev>Max Verstappen</nev>
		<pont>50</pont>
		<csapatid>3</csapatid>
	</versenyzo>
	<versenyzo>
		<rajtszam>44</rajtszam>
		<nev>Lewis Hamilton</nev>
		<pont>50</pont>
		<csapatid>1</csapatid>
	</versenyzo>
	<versenyzo>
		<rajtszam>55</rajtszam>
		<nev>Carlos Sainz</nev>
		<pont>20</pont>
		<csapatid>4</csapatid>
	</versenyzo>
	<versenyzo>
		<rajtszam>77</rajtszam>
		<nev>Valtteri Bottas</nev>
		<pont>50</pont>
		<csapatid>1</csapatid>
	</versenyzo>
</f1>
